### ISSUE TITLE
Which tensorflow version are you using?

### ISSUE THREAD

**Issue by doantientai** [google-research/noisystudent#6]
Hi guys, thanks for the very interesting work! 

Could please provide the list of required packages? I am just trying to reproduce the experiments. Thanks!

**Comment by doantientai** [comment]
So I tried tensorflow-gpu 1.15.0 and it works.

**Comment by v-namtd12** [comment]
@doantientai Do you have teacher ckpt for this repo, I tried to download but it doesn't work. Can you help me with this? Thank you!
