### ISSUE TITLE
Test accuracy?

### ISSUE THREAD

**Issue by huanyuan54** [google-research/noisystudent#8]
测试预训练模型：
I1020 09:23:09.595353 140204815505152 main.py:805] test, results: {'loss': 2.5957024, 'top_1_accuracy': 0.0988783, 'top_5_accuracy': 0.5069914, 'global_step': 0}
与提供97.9%对比不上？

**Comment by Masque555** [comment]
> 测试预训练模型：
> I1020 09:23:09.595353 140204815505152 main.py:805] test, results: {'loss': 2.5957024, 'top_1_accuracy': 0.0988783, 'top_5_accuracy': 0.5069914, 'global_step': 0}
> 与提供97.9%对比不上？

**Comment by Masque555** [comment]
你好请问你调试通得源码可以发一份给我？qq3193346781
